config/routes.rb
CrossPerformanceEvaluation::Application.routes.draw do
  resources :evaluation_terms

  resources :performance_categories

  devise_for :users

  root :to => "home#index"

end

app/models/evaluation_term.rb
class EvaluationTerm < ActiveRecord::Base
  attr_accessible :begin_date, :end_date, :memo
end

app/models/performance_category.rb
class PerformanceCategory < ActiveRecord::Base
  attr_accessible :begin_date, :end_date, :name, :description, :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/evaluation_terms_controller.rb
class EvaluationTermsController < ApplicationController
  # GET /evaluation_terms
  # GET /evaluation_terms.json
  def index
    @evaluation_terms = EvaluationTerm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @evaluation_terms }
    end
  end

  # GET /evaluation_terms/1
  # GET /evaluation_terms/1.json
  def show
    @evaluation_term = EvaluationTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evaluation_term }
    end
  end

  # GET /evaluation_terms/new
  # GET /evaluation_terms/new.json
  def new
    @evaluation_term = EvaluationTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evaluation_term }
    end
  end

  # GET /evaluation_terms/1/edit
  def edit
    @evaluation_term = EvaluationTerm.find(params[:id])
  end

  # POST /evaluation_terms
  # POST /evaluation_terms.json
  def create
    @evaluation_term = EvaluationTerm.new(params[:evaluation_term])

    respond_to do |format|
      if @evaluation_term.save
        format.html { redirect_to @evaluation_term, notice: 'Evaluation term was successfully created.' }
        format.json { render json: @evaluation_term, status: :created, location: @evaluation_term }
      else
        format.html { render action: "new" }
        format.json { render json: @evaluation_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /evaluation_terms/1
  # PUT /evaluation_terms/1.json
  def update
    @evaluation_term = EvaluationTerm.find(params[:id])

    respond_to do |format|
      if @evaluation_term.update_attributes(params[:evaluation_term])
        format.html { redirect_to @evaluation_term, notice: 'Evaluation term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @evaluation_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluation_terms/1
  # DELETE /evaluation_terms/1.json
  def destroy
    @evaluation_term = EvaluationTerm.find(params[:id])
    @evaluation_term.destroy

    respond_to do |format|
      format.html { redirect_to evaluation_terms_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/performance_categories_controller.rb
class PerformanceCategoriesController < ApplicationController
  # GET /performance_categories
  # GET /performance_categories.json
  def index
    @performance_categories = PerformanceCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @performance_categories }
    end
  end

  # GET /performance_categories/1
  # GET /performance_categories/1.json
  def show
    @performance_category = PerformanceCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @performance_category }
    end
  end

  # GET /performance_categories/new
  # GET /performance_categories/new.json
  def new
    @performance_category = PerformanceCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @performance_category }
    end
  end

  # GET /performance_categories/1/edit
  def edit
    @performance_category = PerformanceCategory.find(params[:id])
  end

  # POST /performance_categories
  # POST /performance_categories.json
  def create
    params[:performance_category][:begin_date] = params[:performance_category][:begin_date].delete('-')
    params[:performance_category][:end_date] = params[:performance_category][:end_date].delete('-')

    @performance_category = PerformanceCategory.new(params[:performance_category])

    respond_to do |format|
      if @performance_category.save
        format.html { redirect_to @performance_category, notice: 'Performance category was successfully created.' }
        format.json { render json: @performance_category, status: :created, location: @performance_category }
      else
        format.html { render action: "new" }
        format.json { render json: @performance_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /performance_categories/1
  # PUT /performance_categories/1.json
  def update
    @performance_category = PerformanceCategory.find(params[:id])

    respond_to do |format|
      if @performance_category.update_attributes(params[:performance_category])
        format.html { redirect_to @performance_category, notice: 'Performance category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @performance_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performance_categories/1
  # DELETE /performance_categories/1.json
  def destroy
    @performance_category = PerformanceCategory.find(params[:id])
    @performance_category.destroy

    respond_to do |format|
      format.html { redirect_to performance_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date_integer, separator = '-')
    return "%04d" % (date_integer / 10000) + separator + 
      "%02d" % (date_integer % 10000 / 100) + separator + 
      "%02d" % (date_integer % 100)
  end
end

app/helpers/evaluation_terms_helper.rb
module EvaluationTermsHelper
end

app/helpers/performance_categories_helper.rb
module PerformanceCategoriesHelper
end

app/views/evaluation_terms/_form.html.haml
= form_for @evaluation_term do |f|
  - if @evaluation_term.errors.any?
    #error_explanation
      %h2= "#{pluralize(@evaluation_term.errors.count, "error")} prohibited this evaluation_term from being saved:"
      %ul
        - @evaluation_term.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :begin_date
    = f.number_field :begin_date
  .field
    = f.label :end_date
    = f.number_field :end_date
  .field
    = f.label :memo
    = f.text_field :memo
  .actions
    = f.submit 'Save'

app/views/evaluation_terms/edit.html.haml
%h1 Editing evaluation_term

= render 'form'

= link_to 'Show', @evaluation_term
\|
= link_to 'Back', evaluation_terms_path

app/views/evaluation_terms/index.html.haml
%h1 Listing evaluation_terms

%table
  %tr
    %th Begin date
    %th End date
    %th Memo
    %th
    %th
    %th

  - @evaluation_terms.each do |evaluation_term|
    %tr
      %td= evaluation_term.begin_date
      %td= evaluation_term.end_date
      %td= evaluation_term.memo
      %td= link_to 'Show', evaluation_term
      %td= link_to 'Edit', edit_evaluation_term_path(evaluation_term)
      %td= link_to 'Destroy', evaluation_term, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Evaluation term', new_evaluation_term_path

app/views/evaluation_terms/new.html.haml
%h1 New evaluation_term

= render 'form'

= link_to 'Back', evaluation_terms_path

app/views/evaluation_terms/show.html.haml
%p#notice= notice

%p
  %b Begin date:
  = @evaluation_term.begin_date
%p
  %b End date:
  = @evaluation_term.end_date
%p
  %b Memo:
  = @evaluation_term.memo

= link_to 'Edit', edit_evaluation_term_path(@evaluation_term)
\|
= link_to 'Back', evaluation_terms_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrossPerformanceEvaluation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%=coffee_script_tag do%>
    $('a:not([data-remote]):not([data-behavior]):not([data-skip-pjax])').pjax('[data-pjax-container]')
  <%end%>
  <%= csrf_meta_tags %>
</head>
<body>
    <p class="notice"><%=notice%></p>
    <p class="alert"><%=alert%></p>
    <div id='user_nav'>
      <%if user_signed_in?%>
      Signed in as <%=current_user.email%>. <%=link_to "Sign out", destroy_user_session_path, :method => :delete%>
      <%else%>
        <%=link_to "Sign up", new_user_registration_path%>
        <%=link_to "Sign in", new_user_session_path%>
      <%end%>
    </div>
  <div data-pjax-container>
    <%= yield %>
  </div>
</body>
</html>

app/views/performance_categories/_form.html.haml
= form_for @performance_category do |f|
  - if @performance_category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@performance_category.errors.count, "error")} prohibited this performance_category from being saved:"
      %ul
        - @performance_category.errors.full_messages.each do |msg|
          %li= msg
   
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :begin_date
    = f.text_field :begin_date, :class => "datepicker", :value => format_date(@performance_category.begin_date)
  .field
    = f.label :end_date
    = f.text_field :end_date, :class => "datepicker", :value => format_date(@performance_category.end_date)
  .field
    = f.label :order
    = f.number_field :order, {:style => "text-align:right;"}
  .actions
    = f.submit 'Save'

app/views/performance_categories/edit.html.haml
%h1 Editing performance_category

= render 'form'

= link_to 'Show', @performance_category
\|
= link_to 'Back', performance_categories_path

app/views/performance_categories/index.html.haml
%h1 Listing performance_categories

%table
  %tr
    %th Name
    %th Begin date
    %th End date
    %th Order
    %th
    %th
    %th

  - @performance_categories.each do |performance_category|
    %tr
      %td= performance_category.name
      %td= performance_category.begin_date
      %td= performance_category.end_date
      %td= performance_category.order
      %td= link_to 'Show', performance_category
      %td= link_to 'Edit', edit_performance_category_path(performance_category)
      %td= link_to 'Destroy', performance_category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Performance category', new_performance_category_path

app/views/performance_categories/new.html.haml
%h1 New performance_category

= render 'form'

= link_to 'Back', performance_categories_path

app/views/performance_categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @performance_category.name
%p
  %b Begin date:
  = @performance_category.begin_date
%p
  %b End date:
  = @performance_category.end_date
%p
  %b Order:
  = @performance_category.order

= link_to 'Edit', edit_performance_category_path(@performance_category)
\|
= link_to 'Back', performance_categories_path